sailors_app/urls.py
from django.contrib import admin
from django.urls import path

from sailors_app.views import (
    IndexView, UserTasksView,
    TaskListView, TaskDetailView, TaskCreateView, TaskUpdateView,
    TaskDeleteView,
    PositionListView, PositionDetailView, PositionCreateView,
    PositionUpdateView, PositionDeleteView,
    SailorListView, SailorDetailView, SailorCreateView, SailorUpdateView,
    SailorDeleteView,
    ToggleAssignToTaskView, ToggleChangeIsCompleteView,
)

app_name = "sailors_app"

urlpatterns = [
    path(
        "admin/",
        admin.site.urls
    ),
    path(
        "",
        IndexView.as_view(),
        name="index"
    ),
    path(
        "task/<int:pk>/toggle-assign/",
        ToggleAssignToTaskView.as_view(),
        name="toggle-task-assign",
    ),
    path(
        "task/<int:pk>/change-is-complete/",
        ToggleChangeIsCompleteView.as_view(),
        name="toggle-change-is-complete"
    ),
    path(
        "user_tasks/",
        UserTasksView.as_view(),
        name="user_tasks"
    ),
    path(
        "sailors/",
        SailorListView.as_view(),
        name="sailor-list"
    ),
    path(
        "sailor/<int:pk>/",
        SailorDetailView.as_view(),
        name="sailor-detail"
    ),
    path(
        "sailor/create/",
        SailorCreateView.as_view(),
        name="sailor-create"
    ),
    path(
        "sailor/<int:pk>/update/",
        SailorUpdateView.as_view(),
        name="sailor-update"
    ),
    path(
        "sailor/<int:pk>/delete/",
        SailorDeleteView.as_view(),
        name="sailor-delete"
    ),
    path(
        "tasks/",
        TaskListView.as_view(),
        name="task-list"
    ),
    path(
        "task/<int:pk>/",
        TaskDetailView.as_view(),
        name="task-detail"
    ),
    path(
        "task/create/",
        TaskCreateView.as_view(),
        name="task-create"
    ),
    path(
        "task/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "task/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "positions/",
        PositionListView.as_view(),
        name="position-list"
    ),
    path(
        "position/<int:pk>/",
        PositionDetailView.as_view(),
        name="position-detail"
    ),
    path(
        "position/create/",
        PositionCreateView.as_view(),
        name="position-create"
    ),
    path(
        "position/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update"
    ),
    path(
        "position/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete"
    ),
]

ship_task_manager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path("", include("sailors_app.urls", namespace="sailors_app")),
                  path("accounts/", include("django.contrib.auth.urls")),
                  path('', include('admin_volt.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/footer.html
<footer class="bg-white rounded shadow p-5 mb-4 mt-4">
  <div class="row">
    <div class="col-12 col-md-4 col-xl-6 mb-4 mb-md-0">
      <p class="mb-0 text-center text-lg-start">
        &copy; Sailors App - coded by Haishuk Pavlo.
      </p>
    </div>

    <div class="col-12 col-md-8 col-xl-6 text-center text-lg-start">
      <!-- List -->
      <ul class="list-inline list-group-flush list-group-borderless text-md-end mb-0">
        <li class="list-inline-item px-0 px-sm-2">
          <a href="https://github.com/phaishuk" target="_blank">GitHub</a>
        </li>
        <li class="list-inline-item px-0 px-sm-2">
          <a href="https://www.linkedin.com/in/pavlo-haishuk-87a400157/" target="_blank">LinkedIn</a>
        </li>
        <li class="list-inline-item px-0 px-sm-2">
          <a href="https://www.instagram.com/haishuk_pavlo/" target="_blank">Instagram</a>
        </li>
      </ul>
    </div>
    <div class="justify-content-center">
      <i>"Calm seas never made good sailors! Ancient wisdom"</i>
    </div>
  </div>
</footer>

templates/includes/head.html
{% load static %}

<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<!-- Primary Meta Tags -->
<title>Sailors app</title>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="title" content="Volt Free Bootstrap Dashboard - Settings">
<meta name="author" content="Themesberg">
<meta name="description"
      content="Volt Pro is a Premium Bootstrap 5 Admin Dashboard featuring over 800 components, 10+ plugins and 20 example pages using Vanilla JS.">
<meta name="keywords"
      content="bootstrap 5, bootstrap, bootstrap 5 admin dashboard, bootstrap 5 dashboard, bootstrap 5 charts, bootstrap 5 calendar, bootstrap 5 datepicker, bootstrap 5 tables, bootstrap 5 datatable, vanilla js datatable, themesberg, themesberg dashboard, themesberg admin dashboard"/>
<link rel="canonical" href="https://themesberg.com/product/admin-dashboard/volt-premium-bootstrap-5-dashboard">

<!-- Open Graph / Facebook -->
<meta property="og:type" content="website">
<meta property="og:url" content="https://demo.themesberg.com/volt-pro">
<meta property="og:title" content="Volt Free Bootstrap Dashboard - Settings">
<meta property="og:description"
      content="Volt Pro is a Premium Bootstrap 5 Admin Dashboard featuring over 800 components, 10+ plugins and 20 example pages using Vanilla JS.">
<meta property="og:image"
      content="https://themesberg.s3.us-east-2.amazonaws.com/public/products/volt-pro-bootstrap-5-dashboard/volt-pro-preview.jpg">

<!-- Twitter -->
<meta property="twitter:card" content="summary_large_image">
<meta property="twitter:url" content="https://demo.themesberg.com/volt-pro">
<meta property="twitter:title" content="Volt Free Bootstrap Dashboard - Settings">
<meta property="twitter:description"
      content="Volt Pro is a Premium Bootstrap 5 Admin Dashboard featuring over 800 components, 10+ plugins and 20 example pages using Vanilla JS.">
<meta property="twitter:image"
      content="https://themesberg.s3.us-east-2.amazonaws.com/public/products/volt-pro-bootstrap-5-dashboard/volt-pro-preview.jpg">

<!-- Favicon -->
<link rel="apple-touch-icon" sizes="120x120" href="{% static 'assets/img/favicon/apple-touch-icon.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'assets/img/favicon/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/img/favicon/favicon-16x16.png' %}">
<link rel="manifest" href="{% static 'assets/img/favicon/site.webmanifest' %}">
<link rel="mask-icon" href="{% static 'assets/img/favicon/safari-pinned-tab.svg' %}" color="#ffffff">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="theme-color" content="#ffffff">

<!-- Sweet Alert -->
<link type="text/css" href="{% static 'vendor/sweetalert2/dist/sweetalert2.min.css' %}" rel="stylesheet">

<!-- Notyf -->
<link type="text/css" href="{% static 'vendor/notyf/notyf.min.css' %}" rel="stylesheet">

<!-- Volt CSS -->
<link type="text/css" href="{% static 'css/volt.css' %}" rel="stylesheet">

<!-- NOTICE: You can use the _analytics.html partial to include production code specific code & trackers -->

templates/includes/navigation.html
{% load static %}

<nav class="navbar navbar-top navbar-expand navbar-dashboard navbar-dark ps-0 pe-2 pb-0">
  <div class="container-fluid px-0">
    <div class="d-flex justify-content-between w-100" id="navbarSupportedContent">
      <div class="d-flex align-items-center">
      </div>
      <!-- Navbar links -->
      <ul class="navbar-nav align-items-center">
        <a href="{% url 'logout' %}?next={{ request.path }}" class="btn btn-secondary">
          Logout
        </a>
        <li class="nav-item dropdown ms-lg-3">
          <a class="nav-link dropdown-toggle pt-1 px-0" href="#" role="button" data-bs-toggle="dropdown"
             aria-expanded="false">
            <div class="media d-flex align-items-center">
              <img class="avatar rounded-circle" alt="Image placeholder"
                   src="{% static 'assets/img/team/profile-picture-3.jpg' %}">
              <div class="media-body ms-2 text-dark align-items-center d-none d-lg-block">
                <a href="{{ user.get_absolute_url }}">
                  <span class="mb-0 font-small fw-bold text-gray-900">{{ user.first_name }} {{ user.last_name }}</span>
                </a>
              </div>
            </div>
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination" style="margin-top: 10px;">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}

    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>

    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/search_input_form_position&task.html
{% load crispy_forms_filters %}
<form action="" method="get" class="form-inline w-100" style="margin-bottom: 20px;">
  <div class="d-flex" style="width: 300px">
    <div class="flex-grow-1">
      {{ name|crispy }}
    </div>
    <input type="submit" value="🔍" class="btn btn-outline-secondary shadow">
  </div>
</form>

templates/includes/search_input_form_sailor.html
{#<form action="" method="get" class="form-inline" style="margin-bottom: 20px;">#}
{#  {{ first_name }}#}
{#  <input type="submit" value="🔍" class="btn btn-secondary">#}
{#</form>#}

{% load crispy_forms_filters %}
<form action="" method="get" class="form-inline w-100" style="margin-bottom: 20px;">
  <div class="d-flex" style="width: 300px;">
    <div class="flex-grow-1">
      {{ first_name|crispy }}
    </div>
    <input type="submit" value="🔍" class="btn btn-outline-secondary shadow">

  </div>
</form>

templates/includes/sidebar.html
{% load i18n static admin_volt %}

<nav id="sidebarMenu" class="sidebar d-lg-block bg-gray-800 text-white collapse" data-simplebar>
  <div class="sidebar-inner px-4 pt-3">
    <div class="user-card d-flex d-md-none align-items-center justify-content-between justify-content-md-center pb-4">
      <div class="d-flex align-items-center">
        <div class="avatar-lg me-4">
          <img src="{% static 'assets/img/team/profile-picture-3.jpg' %}"
               class="card-img-top rounded-circle border-white"
               alt="Bonnie Green">
        </div>
        <div class="d-block">
          <h2 class="h5 mb-3">Hi, Jane</h2>
          <a href="{% url 'logout' %}" class="btn btn-secondary btn-sm d-inline-flex align-items-center">
            <svg class="icon icon-xxs me-1" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                 xmlns="http://www.w3.org/2000/svg">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"></path>
            </svg>
            Sign Out
          </a>
        </div>
      </div>
      <div class="collapse-close d-md-none">
        <a href="#sidebarMenu" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu"
           aria-expanded="true" aria-label="Toggle navigation">
          <svg class="icon icon-xs" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
                  d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                  clip-rule="evenodd"></path>
          </svg>
        </a>
      </div>
    </div>
    <ul class="nav flex-column pt-3 pt-md-0">

      <li class="nav-item">
        <a href="{% url 'sailors_app:index' %}" class="nav-link">
          <span class="sidebar-text">Home</span>
        </a>
      </li>

      <li class="nav-item">
        <a href="{% url 'sailors_app:user_tasks' %}" class="nav-link">
          <span class="sidebar-text">My tasks</span>
        </a>
      </li>

      <li class="nav-item">
        <a href="{% url 'sailors_app:sailor-list' %}" class="nav-link">
          <span class="sidebar-text">All sailors</span>
        </a>
      </li>

      <li class="nav-item">
        <a href="{% url 'sailors_app:task-list' %}" class="nav-link">
          <span class="sidebar-text">All tasks</span>
        </a>
      </li>

      <li class="nav-item">
        <a href="{% url 'sailors_app:position-list' %}" class="nav-link">
          <span class="sidebar-text">All positions</span>
        </a>
      </li>
    </ul>
  </div>
</nav>

templates/includes/theme-settings.html
{# this template have to be empty to avoid false inheritance.#}
{# On the page doesn't provide any code inherited from the original template #}