sailors_app/urls.py
from django.contrib import admin
from django.urls import path

from sailors_app.views import (
    IndexView, UserTasksView,
    TaskListView, TaskDetailView, TaskCreateView, TaskUpdateView,
    TaskDeleteView,
    PositionListView, PositionDetailView, PositionCreateView,
    PositionUpdateView, PositionDeleteView,
    SailorListView, SailorDetailView, SailorCreateView, SailorUpdateView,
    SailorDeleteView,
    ToggleAssignToTaskView, ToggleChangeIsCompleteView,
)

app_name = "sailors_app"

urlpatterns = [
    path(
        "admin/",
        admin.site.urls
    ),
    path(
        "",
        IndexView.as_view(),
        name="index"
    ),
    path(
        "task/<int:pk>/toggle-assign/",
        ToggleAssignToTaskView.as_view(),
        name="toggle-task-assign",
    ),
    path(
        "task/<int:pk>/change-is-complete/",
        ToggleChangeIsCompleteView.as_view(),
        name="toggle-change-is-complete"
    ),
    path(
        "user_tasks/",
        UserTasksView.as_view(),
        name="user_tasks"
    ),
    path(
        "sailors/",
        SailorListView.as_view(),
        name="sailor-list"
    ),
    path(
        "sailor/<int:pk>/",
        SailorDetailView.as_view(),
        name="sailor-detail"
    ),
    path(
        "sailor/create/",
        SailorCreateView.as_view(),
        name="sailor-create"
    ),
    path(
        "sailor/<int:pk>/update/",
        SailorUpdateView.as_view(),
        name="sailor-update"
    ),
    path(
        "sailor/<int:pk>/delete/",
        SailorDeleteView.as_view(),
        name="sailor-delete"
    ),
    path(
        "tasks/",
        TaskListView.as_view(),
        name="task-list"
    ),
    path(
        "task/<int:pk>/",
        TaskDetailView.as_view(),
        name="task-detail"
    ),
    path(
        "task/create/",
        TaskCreateView.as_view(),
        name="task-create"
    ),
    path(
        "task/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "task/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "positions/",
        PositionListView.as_view(),
        name="position-list"
    ),
    path(
        "position/<int:pk>/",
        PositionDetailView.as_view(),
        name="position-detail"
    ),
    path(
        "position/create/",
        PositionCreateView.as_view(),
        name="position-create"
    ),
    path(
        "position/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update"
    ),
    path(
        "position/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete"
    ),
]

ship_task_manager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path("", include("sailors_app.urls", namespace="sailors_app")),
                  path("accounts/", include("django.contrib.auth.urls")),
                  path('', include('admin_volt.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sailors_app/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models import Case, Value, When, CharField
from django.urls import reverse


class Position(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"{self.name}"


class Sailor(AbstractUser):
    position = models.ForeignKey(
        to=Position,
        on_delete=models.SET_DEFAULT,
        default=8
    )
    board_number = models.CharField(max_length=255, unique=True)

    class Meta:
        verbose_name = "sailor"
        verbose_name_plural = "sailors"

    def __str__(self):
        return f"{self.username} ({self.position})"

    def get_absolute_url(self):
        return reverse("sailors_app:sailor-detail", kwargs={"pk": self.pk})


class TaskType(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.name}"


class Task(models.Model):
    PRIORITY_LEVEL = (
        ("low", "LOW"),
        ("middle", "MIDDLE"),
        ("high", "HIGH"),
    )

    name = models.CharField(max_length=255)
    description = models.TextField(max_length=255)
    deadline = models.DateField()
    is_completed = models.BooleanField()
    priority = models.CharField(max_length=10, choices=PRIORITY_LEVEL)
    task_type = models.ForeignKey(to=TaskType, on_delete=models.CASCADE)
    assignees = models.ManyToManyField(Sailor, related_name="tasks")

    class Meta:
        ordering = [
            Case(
                When(priority='high', then=Value(1)),
                When(priority='middle', then=Value(2)),
                default=Value(3),
                output_field=CharField()
            ),
            'deadline',
        ]

    def __str__(self):
        return f"{self.name}"

sailors_app/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from sailors_app.models import Sailor, Task


def validate_board_number(board_number):
    if not (board_number[0] == "$" and board_number[3] == "_"):
        raise ValidationError(
            "Ensure that the value's first letter is '$' and fourth is '_'"
        )
    if not (board_number[1:3].isupper() and board_number[1:3].isalpha()):
        raise ValidationError(
            "Ensure that the value's second and third letter "
            "starts with  uppercase letters"
        )
    if not board_number[-6:].isdigit():
        raise ValidationError("Ensure that value ends with 6 digits")
    if not len(board_number) == 10:
        raise ValidationError(
            "Ensure that length of your licence exactly 10 characters"
        )
    return board_number


class SailorCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = Sailor
        fields = UserCreationForm.Meta.fields + ("position", "board_number",)

    def clean_board_number(self):
        board_number = self.cleaned_data["board_number"]
        return validate_board_number(board_number)


class SailorUpdateForm(forms.ModelForm):
    old_password = forms.CharField(widget=forms.PasswordInput, required=False)
    new_password = forms.CharField(widget=forms.PasswordInput, required=False)
    confirm_password = forms.CharField(widget=forms.PasswordInput, required=False)

    class Meta:
        model = Sailor
        fields = (
            "username", "old_password", "new_password", "confirm_password",
            "first_name", "last_name", "email", "position", "board_number",
        )

    def clean_old_password(self):
        old_password = self.cleaned_data.get("old_password")
        if old_password and not self.instance.check_password(old_password):
            raise forms.ValidationError(
                "The old password is incorrect."
            )
        return old_password

    def clean(self):
        cleaned_data = super().clean()
        old_password = self.cleaned_data.get("old_password")
        new_password = cleaned_data.get("new_password")
        confirm_password = cleaned_data.get("confirm_password")
        if (new_password or confirm_password) and not old_password:
            raise forms.ValidationError(
                "Please enter your current password to set a new password."
            )
        if confirm_password and not new_password:
            raise forms.ValidationError(
                "Please enter a new password before confirm password."
            )
        if new_password and not confirm_password:
            raise forms.ValidationError(
                "Please confirm your password."
            )
        if new_password and confirm_password and (
                new_password != confirm_password
        ):
            raise forms.ValidationError(
                "The new passwords do not match."
            )

        return cleaned_data

    def save(self, commit=True):
        sailor = super().save(commit=False)
        new_password = self.cleaned_data.get("new_password")
        if new_password:
            sailor.set_password(new_password)
        if commit:
            sailor.save()
        return sailor

    def clean_board_number(self):
        board_number = self.cleaned_data["board_number"]
        return validate_board_number(board_number)


class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = "__all__"

    assignees = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )


class SearchSailors(forms.Form):
    first_name = forms.CharField(
        max_length=50,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by sailor's name"}
        ),
    )


class SearchTasks(forms.Form):
    name = forms.CharField(
        max_length=50,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by task's name"}
        ),
    )


class SearchPositions(forms.Form):
    name = forms.CharField(
        max_length=50,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by position's name"}
        ),
    )

sailors_app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic

from sailors_app.forms import (
    SailorCreationForm, SailorUpdateForm, TaskForm, SearchSailors,
    SearchPositions, SearchTasks
)
from sailors_app.models import Task, Sailor, Position


class IndexView(LoginRequiredMixin, generic.TemplateView):
    template_name = "sailors_app/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        num_visits = self.request.session.get("num_visits", 0) + 1
        self.request.session["num_visits"] = num_visits
        context["num_visits"] = num_visits
        context["num_tasks"] = Task.objects.count()
        context["num_sailors"] = Sailor.objects.count()
        context["num_positions"] = Position.objects.count()
        return context


class ToggleAssignToTaskView(LoginRequiredMixin, generic.View):

    @staticmethod
    def post(request, pk):
        sailor = get_object_or_404(Sailor, id=request.user.id)
        task = get_object_or_404(Task, id=pk)
        if task in sailor.tasks.all():
            sailor.tasks.remove(task)
        else:
            sailor.tasks.add(task)
        return HttpResponseRedirect(reverse_lazy(
            "sailors_app:task-detail", args=[pk]
        ))


class ToggleChangeIsCompleteView(LoginRequiredMixin, generic.View):

    @staticmethod
    def post(request, pk):
        task = get_object_or_404(Task, id=pk)
        task.is_completed = not task.is_completed
        task.save()

        return redirect(request.META.get("HTTP_REFERER"))


class UserTasksView(LoginRequiredMixin, generic.ListView):
    model = Task
    template_name = "sailors_app/user_tasks.html"
    context_object_name = "tasks"

    def get_queryset(self):
        sailor = Sailor.objects.get(id=self.request.user.id)
        return sailor.tasks.all()


class SailorListView(LoginRequiredMixin, generic.ListView):
    model = Sailor
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(SailorListView, self).get_context_data(**kwargs)

        title = self.request.GET.get("title", "")
        context["first_name"] = SearchSailors(initial={
            "title": title
        })

        return context

    def get_queryset(self):
        queryset = Sailor.objects.select_related("position")
        first_name = self.request.GET.get("first_name")

        if first_name:
            return queryset.filter(first_name__icontains=first_name)
        return queryset


class SailorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Sailor
    queryset = Sailor.objects.prefetch_related("tasks__assignees")
    paginate_by = 5


class SailorCreateView(LoginRequiredMixin, generic.CreateView):
    model = Sailor
    form_class = SailorCreationForm
    success_url = reverse_lazy("sailors_app:sailor-list")


class SailorUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Sailor
    form_class = SailorUpdateForm
    success_url = reverse_lazy("sailors_app:sailor-list")


class SailorDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Sailor
    success_url = reverse_lazy("sailors_app:sailor-list")


class TaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    form_class = TaskForm
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskListView, self).get_context_data(**kwargs)

        title = self.request.GET.get("title", "")
        context["name"] = SearchTasks(initial={
            "title": title
        })

        return context

    def get_queryset(self):
        queryset = Task.objects.all()
        name = self.request.GET.get("name")

        if name:
            return queryset.filter(name__icontains=name)
        return queryset


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("sailors_app:task-list")


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("sailors_app:task-list")


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy("sailors_app:task-list")


class PositionListView(LoginRequiredMixin, generic.ListView):
    model = Position
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PositionListView, self).get_context_data(**kwargs)

        title = self.request.GET.get("title", "")
        context["name"] = SearchPositions(initial={
            "title": title
        })

        return context

    def get_queryset(self):
        queryset = Position.objects.all()
        name = self.request.GET.get("name")

        if name:
            return queryset.filter(name__icontains=name)
        return queryset


class PositionDetailView(LoginRequiredMixin, generic.DetailView):
    model = Position


class PositionCreateView(LoginRequiredMixin, generic.CreateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("sailors_app:position-list")


class PositionUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("sailors_app:position-list")


class PositionDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Position
    success_url = reverse_lazy("sailors_app:position-list")

templates/sailors_app/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

  <div class="py-4">
    <h1 style="text-align: center;">Welcome to the ship!</h1>
  </div>
  <div class="row">
    <div class="col-12 col-sm-6 col-xl-4 mb-4">
      <div class="card border-0 shadow">
        <div class="card-body">
          <div class="row d-block d-xl-flex align-items-center">
            <div
                class="col-12 col-xl-5 text-xl-center mb-3 mb-xl-0 d-flex align-items-center justify-content-xl-center">
              <div class="icon-shape icon-shape-primary rounded me-4 me-sm-0">
                <svg class="icon" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                  <path
                      d="M13 6a3 3 0 11-6 0 3 3 0 016 0zM18 8a2 2 0 11-4 0 2 2 0 014 0zM14 15a4 4 0 00-8 0v3h8v-3zM6 8a2 2 0 11-4 0 2 2 0 014 0zM16 18v-3a5.972 5.972 0 00-.75-2.906A3.005 3.005 0 0119 15v3h-3zM4.75 12.094A5.973 5.973 0 004 15v3H1v-3a3 3 0 013.75-2.906z">
                  </path>
                </svg>
              </div>
              <div class="d-sm-none">
                <h2 class="h5">Sailors</h2>
                <h3 class="fw-extrabold mb-1">{{ num_sailors }} people</h3>
              </div>
            </div>
            <div class="col-12 col-xl-7 px-xl-0">
              <div class="d-none d-sm-block">
                <h2 class="h6 text-gray-400 mb-0">Sailors</h2>
                <h3 class="fw-extrabold mb-2">{{ num_sailors }} people</h3>
              </div>
              <small class="d-flex align-items-center text-gray-500">
                Total quantity of seamen on the board ready to beat sea
              </small>
              <div class="small d-flex mt-1">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-12 col-sm-6 col-xl-4 mb-4">
      <div class="card border-0 shadow">
        <div class="card-body">
          <div class="row d-block d-xl-flex align-items-center">
            <div
                class="col-12 col-xl-5 text-xl-center mb-3 mb-xl-0 d-flex align-items-center justify-content-xl-center">
              <div class="icon-shape icon-shape-secondary rounded me-4 me-sm-0">
                <svg class="icon" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd"
                        d="M10 2a4 4 0 00-4 4v1H5a1 1 0 00-.994.89l-1 9A1 1 0 004 18h12a1 1 0 00.994-1.11l-1-9A1 1 0 0015 7h-1V6a4 4 0 00-4-4zm2 5V6a2 2 0 10-4 0v1h4zm-6 3a1 1 0 112 0 1 1 0 01-2 0zm7-1a1 1 0 100 2 1 1 0 000-2z"
                        clip-rule="evenodd"></path>
                </svg>
              </div>
              <div class="d-sm-none">
                <h2 class="fw-extrabold h5">Positions</h2>
                <h3 class="mb-1">{{ num_positions }} specialities</h3>
              </div>
            </div>
            <div class="col-12 col-xl-7 px-xl-0">
              <div class="d-none d-sm-block">
                <h2 class="h6 text-gray-400 mb-0">Positions</h2>
                <h3 class="fw-extrabold mb-2">{{ num_positions }} specialities</h3>
              </div>
              <small class="d-flex align-items-center text-gray-500">
                Total quantity of positions available on the board
              </small>
              <div class="small d-flex mt-1">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-12 col-sm-6 col-xl-4 mb-4">
      <div class="card border-0 shadow">
        <div class="card-body">
          <div class="row d-block d-xl-flex align-items-center">
            <div
                class="col-12 col-xl-5 text-xl-center mb-3 mb-xl-0 d-flex align-items-center justify-content-xl-center">
              <div class="icon-shape icon-shape-tertiary rounded me-4 me-sm-0">
                <svg class="icon" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd"
                        d="M3 3a1 1 0 000 2v8a2 2 0 002 2h2.586l-1.293 1.293a1 1 0 101.414 1.414L10 15.414l2.293 2.293a1 1 0 001.414-1.414L12.414 15H15a2 2 0 002-2V5a1 1 0 100-2H3zm11.707 4.707a1 1 0 00-1.414-1.414L10 9.586 8.707 8.293a1 1 0 00-1.414 0l-2 2a1 1 0 101.414 1.414L8 10.414l1.293 1.293a1 1 0 001.414 0l4-4z"
                        clip-rule="evenodd"></path>
                </svg>
              </div>
              <div class="d-sm-none">
                <h2 class="fw-extrabold h5"> Tasks</h2>
                <h3 class="mb-1">{{ num_tasks }} challenges</h3>
              </div>
            </div>
            <div class="col-12 col-xl-7 px-xl-0">
              <div class="d-none d-sm-block">
                <h2 class="h6 text-gray-400 mb-0"> Tasks</h2>
                <h3 class="fw-extrabold mb-2">{{ num_tasks }} challenges</h3>
              </div>
              <small class="text-gray-500">
                Total quantity of the tasks have to be done on the board
              </small>
              <div class="small d-flex mt-1">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="bg-white rounded shadow p-3 mx-auto" style="margin: 0 10px; width: 240px; text-align: center">
      <div class="row">
        You visited this page {{ num_visits }} time(s).
      </div>
    </div>


  </div>

{% endblock content %}

templates/sailors_app/position_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete position <strong>{{ position.name }}</strong> ? </h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/sailors_app/position_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Position name: {{ position.name }}
  </h1>

{% endblock %}

templates/sailors_app/position_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} position </h1>
  <form action="" method="post" novalidate style="margin-bottom: 10px">
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary" style="margin-top: 10px">
  </form>
{% endblock %}

templates/sailors_app/position_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Positions list
  </h1>
  <a href="{% url 'sailors_app:position-create' %}" class="btn btn-primary link-to-page" style="margin-bottom: 20px;">
      Create position
  </a>
    {% include "includes/search_input_form_position&task.html" %}
  <div class="card card-body border-0 shadow table-wrapper table-responsive">
    {% if position_list %}
      <table class="table table-hover">
        <thead>
          <tr>
            <th class="border-gray-200">Name</th>
            <th class="border-gray-200">Update</th>
            <th class="border-gray-200">Delete</th>
          </tr>
        </thead>

        {% for position in position_list %}
          <tr>
            <td>
              <u><a href="{% url "sailors_app:position-detail" pk=position.id %} "> {{ position.name }}</a></u>
            </td>
            <td>
              <a href="{% url "sailors_app:position-update" pk=position.id %}">Update</a>
            </td>
            <td>
              <a href="{% url "sailors_app:position-delete" pk=position.id %}" style="color: red">
                Delete
              </a>
            </td>
          </tr>
        {% endfor %}
      </table>
  </div>
    {% else %}
        <p>There are no positions in the service.</p>
    {% endif %}
{% endblock %}

templates/sailors_app/sailor_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete sailor <strong>{{ sailor.username }}</strong> who is {{ sailor.position }}?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/sailors_app/sailor_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Sailor</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/sailors_app/sailor_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Sailors list
  </h1>
  <a href="{% url 'sailors_app:sailor-create' %}" class="btn btn-primary link-to-page" style="margin-bottom: 20px">
    Create sailor
  </a>
  {% include "includes/search_input_form_sailor.html" %}
  <div class="card card-body border-0 shadow table-wrapper table-responsive">
    {% if sailor_list %}
      <table class="table table-hover">
        <thead>
        <tr>
          <th class="border-gray-200">Username</th>
          <th class="border-gray-200">First name</th>
          <th class="border-gray-200">Last name</th>
          <th class="border-gray-200">Position</th>
          <th class="border-gray-200">Update</th>
          <th class="border-gray-200">Delete</th>
        </tr>
        </thead>

        {% for sailor in sailor_list %}
          <tr>
            <td>
              <a href="{{ sailor.get_absolute_url }}">
                <u>{{ sailor.username }}</u>
                {% if user == sailor %} <strong style="color: green">(Me)</strong> {% endif %}
              </a>
            </td>
            <td>{{ sailor.first_name }}</td>
            <td>{{ sailor.last_name }}</td>
            <td>{{ sailor.position }}</td>
            <td>
              <a href="{% url 'sailors_app:sailor-update' pk=sailor.id %}">
                Update
              </a>
            </td>
            <td>
              <a href="{% url 'sailors_app:sailor-delete' pk=sailor.id %}" style="color: red">
                Delete
              </a>
            </td>
          </tr>
        {% endfor %}

      </table>
    {% else %}
      <p>There are no sailors in the service.</p>
    {% endif %}
  </div>
{% endblock %}

templates/sailors_app/task_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    {{ task.name }}
  </h1>
  <h2>Description:</h2>
  <h5><i>{{ task.description }}</i></h5>
  <form method="POST" action="{% url 'sailors_app:toggle-task-assign' pk=task.id %}">
    {% csrf_token %}
    {% if task in user.tasks.all %}
      <button type="submit" class="btn btn-danger link-to-page">
        Delete me from this task
      </button>
    {% else %}
      <button type="submit" class="btn btn-success link-to-page">
        Assign me to this task
      </button>
    {% endif %}
  </form>
  <h4 style="margin-top: 30px;">
    See assignees below:
  </h4>
  <hr>
  <ul>
    {% for assignee in task.assignees.all %}
      <div class="card card-body shadow table-wrapper table-responsive">
        <table>
          <tr>
            <td>
              <strong>Username:</strong> {{ assignee.username }} <br>
              <strong>Full name:</strong> {{ assignee.first_name }} {{ assignee.last_name }} <br>
              <strong>Position:</strong> {{ assignee.position }}<br>
            </td>
          </tr>
        </table>
      </div>

    {% endfor %}
  </ul>
{% endblock %}

templates/sailors_app/task_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Tasks list
  </h1>
  <a href="{% url 'sailors_app:task-create' %}" class="btn btn-primary link-to-page" style="margin-bottom: 20px">
    Create task
  </a>
  {% include "includes/search_input_form_position&task.html" %}
  <div class="card card-body border-0 shadow table-wrapper table-responsive">
    {% if  task_list %}
      <table class="table table-hover">
        <thead>
        <tr>
          <th class="border-grey-200">Task</th>
          <th class="border-grey-200">Priority</th>
          <th class="border-grey-200">Is_completed</th>
          <th class="border-grey-200">Deadline</th>
          <th class="border-grey-200">Update</th>
          <th class="border-grey-200">Delete</th>
        </tr>
        </thead>
        {% for task in task_list %}
          <tr>
            <td>
              <u><a href="{% url "sailors_app:task-detail" pk=task.id %} ">{{ task.name }}</a></u>
            </td>
            <td>
              {{ task.priority }}
            </td>
            <td>
              {% if task.is_completed %}
                <form action="{% url 'sailors_app:toggle-change-is-complete' pk=task.id %}" method="POST"
                      class="d-inline">
                  {% csrf_token %}
                  <input type="hidden" name="is_completed" value="False">
                  <button type="submit" class="btn btn-secondary link-to-page">Undo</button>
                </form>
              {% else %}
                <form action="{% url 'sailors_app:toggle-change-is-complete' pk=task.id %}" method="POST"
                      class="d-inline">
                  {% csrf_token %}
                  <input type="hidden" name="is_completed" value="True">
                  <button type="submit" class="btn btn-primary link-to-page">Mark complete</button>
                </form>
              {% endif %}
            </td>
            <td>
              {{ task.deadline }}
            </td>
            <td>
              <a href="{% url 'sailors_app:task-update' pk=task.id %}">
                Update
              </a>
            </td>
            <td>
              <a href="{% url 'sailors_app:task-delete' pk=task.id %}" style="color: red">
                Delete
              </a>

            </td>
          </tr>

        {% endfor %}
      </table>

    {% else %}
      <p>There are no tasks on the service</p>
    {% endif %}
  </div>
{% endblock %}